## Device settings, provide one of the following:
# 1. device_id (most secure if you use multiple devices)
device_id: "03600A3B" 
# 2. port + baudrate information
# port: '/dev/ttyUSB0' 
# baudrate: 115200

frame_id: "imu_link"

# Message publishers
publisher_queue_size: 5
pub_imu: true
pub_quaternion: false
pub_mag: false
pub_angular_velocity: false
pub_acceleration: false
pub_free_acceleration: false
pub_dq: false
pub_dv: false
pub_sampletime: false
pub_temperature: false
pub_pressure: false
pub_gnss: false
pub_twist: false
pub_transform: false
pub_positionLLA: false
pub_velocity: true

## Sensor standard deviation [x,y,z] (optional)
## The value overrides the covariance matrix in sensor_msgs/Imu
linear_acceleration_stddev: [0, 0, 0] # [m/s^2]
angular_velocity_stddev: [0, 0, 0] # [rad/s]
orientation_stddev: [0, 0, 0] # [rad]
magnetic_field_stddev: [0, 0, 0] # [Tesla]
